export const data = [
  {
    id: 798400,
    title: "Spicy Black-Eyed Pea Curry with Swiss Chard and Roasted Eggplant",
    readyInMinutes: 45,
    servings: 6,
    image: "https://spoonacular.com/recipeImages/798400-312x231.jpg",
    cuisines: ["Indian", "Asian"],
    dishTypes: [
      "antipasti",
      "starter",
      "snack",
      "appetizer",
      "antipasto",
      "hor d'oeuvre",
    ],
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
  },
  {
    id: 798401,
    title: "Spicy Black-Eyed Pea Curry with Swiss Chard and Roasted Eggplant",
    readyInMinutes: 45,
    servings: 6,
    image: "https://spoonacular.com/recipeImages/798400-312x231.jpg",
    cuisines: ["Indian", "Asian"],
    dishTypes: [
      "antipasti",
      "starter",
      "snack",
      "appetizer",
      "antipasto",
      "hor d'oeuvre",
    ],
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
  },
  {
    id: 798402,
    title: "Spicy Black-Eyed Pea Curry with Swiss Chard and Roasted Eggplant",
    readyInMinutes: 45,
    servings: 6,
    image: "https://spoonacular.com/recipeImages/798400-312x231.jpg",
    cuisines: ["Indian", "Asian"],
    dishTypes: [
      "antipasti",
      "starter",
      "snack",
      "appetizer",
      "antipasto",
      "hor d'oeuvre",
    ],
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
  },
  {
    id: 798403,
    title: "Spicy Black-Eyed Pea Curry with Swiss Chard and Roasted Eggplant",
    readyInMinutes: 45,
    servings: 6,
    image: "https://spoonacular.com/recipeImages/798400-312x231.jpg",
    cuisines: ["Indian", "Asian"],
    dishTypes: [
      "antipasti",
      "starter",
      "snack",
      "appetizer",
      "antipasto",
      "hor d'oeuvre",
    ],
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
  },
  {
    id: 798404,
    title: "Spicy Black-Eyed Pea Curry with Swiss Chard and Roasted Eggplant",
    readyInMinutes: 45,
    servings: 6,
    image: "https://spoonacular.com/recipeImages/798400-312x231.jpg",
    cuisines: ["Indian", "Asian"],
    dishTypes: [
      "antipasti",
      "starter",
      "snack",
      "appetizer",
      "antipasto",
      "hor d'oeuvre",
    ],
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
  },
  {
    id: 798405,
    title: "Spicy Black-Eyed Pea Curry with Swiss Chard and Roasted Eggplant",
    readyInMinutes: 45,
    servings: 6,
    image: "https://spoonacular.com/recipeImages/798400-312x231.jpg",
    cuisines: ["Indian", "Asian"],
    dishTypes: [
      "antipasti",
      "starter",
      "snack",
      "appetizer",
      "antipasto",
      "hor d'oeuvre",
    ],
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
  },
  {
    id: 798406,
    title: "Spicy Black-Eyed Pea Curry with Swiss Chard and Roasted Eggplant",
    readyInMinutes: 45,
    servings: 6,
    image: "https://spoonacular.com/recipeImages/798400-312x231.jpg",
    cuisines: ["Indian", "Asian"],
    dishTypes: [
      "antipasti",
      "starter",
      "snack",
      "appetizer",
      "antipasto",
      "hor d'oeuvre",
    ],
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
  },
  {
    id: 798407,
    title: "Spicy Black-Eyed Pea Curry with Swiss Chard and Roasted Eggplant",
    readyInMinutes: 45,
    servings: 6,
    image: "https://spoonacular.com/recipeImages/798400-312x231.jpg",
    cuisines: ["Indian", "Asian"],
    dishTypes: [
      "antipasti",
      "starter",
      "snack",
      "appetizer",
      "antipasto",
      "hor d'oeuvre",
    ],
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
  },
];
